---
- hosts: localhost
  become: true
  become_method: sudo
  vars_files:
  - us-east-1.yaml
  tasks:
  - name: Create_ec2_instance
    ec2:
      key_name:          "{{key_name}}"
      instance_type:     "{{instance_type}}"
      image:             "{{image}}"
      #wait: yes
      group_id:           "{{group_id}}"
      count:             "{{count}}"
      vpc_subnet_id:     "{{vpc_subnet_id}}"
      assign_public_ip:  "{{assign_public_ip}}"
      region:            "{{region}}"