---
- hosts: localhost
  tasks:
  - name: example using security group rule descriptions
    ec2_group:
      name: Allow_80
      description: sg with rule descriptions
      #vpc_id: vpc-xxxxxxxx
      #profile: "{{ aws_profile }}"
      region: us-east-1
      #state: absent
      rules:
        - proto: tcp
          ports:
          - 80
          cidr_ip: 0.0.0.0/0
          #rule_desc: allow all on port 80