---
- hosts: localhost
  tasks:
  - name: create VPC
    ec2_vpc_net:
      name: dev
      cidr_block: 10.1.0.0/16
      region: us-east-1
      #state: absent
      #tags:
        #module: ec2_vpc_net
        #this: works
      #tenancy: dedicated